### PR TITLE
Remove outdated user section from the README

### PR DESCRIPTION
**Pull request by jlsjonas**
According to the commit stats of https://github.com/grocy/grocy/commit/27169e1428ca307401a197fa679d6de6b8e7c607, the underlying issue was released as part of grocy 3.1.0 on Jul 16, 2021.

Unless this is still an ongoing issue with the card, we should remove this section to avoid confusing new users.

Thanks for the great looking card!

### CODE REVIEW

**Comment by jlsjonas** [comment]
I somehow missed the reference from the user_id option during my first read; as the underlying issue should be resolved, what's needed to get it resolved on the card's side?

**Comment by isabellaalstrom** [comment]
Have you tried it from the card now?

**Comment by jlsjonas** [comment]
@isabellaalstrom I've just validated that it works both for adding tasks and checking off chores! 🎉

**Comment by isabellaalstrom** [comment]
Great, thanks!

**Pull request merged**
