### PR TITLE
Added several appearance options plus collapsible overflow area support

### PR DESCRIPTION
**Pull request by clarinetJWD**
This request includes a major revamp of the card's appearance (see the readme on my fork for details on all changes). Most changes require the user to add optional parameters, so aside from switching a couple colors and fonts to use CSS variables from the theme, existing users should not see changes.

The major change is the addition of "Overflow" which lets you have a collapsible area containing all the tasks that didn't fit on the card because of the show_quantity parameter. This way, the user can still see all tasks without taking up a ton of room on the dashboard.

Attached is a word doc outlining all changes.

[Grocy Card Changelog.docx](https://github.com/isabellaalstrom/lovelace-grocy-chores-card/files/9270714/Grocy.Card.Changelog.docx)

### CODE REVIEW

**Comment by isabellaalstrom** [comment]
Great, thanks! Can I merge now or do you expect more commits? :)

**Comment by clarinetJWD** [comment]
Oops, sorry, I don't check my email very often on weekends. Thanks for the merge, there will be more coming, but I'll try to batch things so you're not reviewing/merging too often.
On 8/8/2022 7:09:27 AM, Isabella Gross Alström ***@***.***> wrote:
Merged #77 [https://github.com/isabellaalstrom/lovelace-grocy-chores-card/pull/77] into master.

**Comment by clarinetJWD** [comment]
I've been looking at some of the other feature requests, and the "skip chore" item caught my eye. I see that the integration functionality is currently in a pre-release version. Do you know when to expect that to be officially released? I don't want to make changes right now that rely on beta versions.

Thanks!
On 8/8/2022 8:54:37 AM, Joe Dombrowski ***@***.***> wrote:
Oops, sorry, I don't check my email very often on weekends. Thanks for the merge, there will be more coming, but I'll try to batch things so you're not reviewing/merging too often.
On 8/8/2022 7:09:27 AM, Isabella Gross Alström ***@***.***> wrote:
Merged #77 [https://github.com/isabellaalstrom/lovelace-grocy-chores-card/pull/77] into master.

**Comment by isabellaalstrom** [comment]
I can release it now! :)

**Pull request merged**
